# Generated by Django 4.2.1 on 2023-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_statusapplication_rename_friends_user_applications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.DeleteModel(
            name='StatusApplication',
        ),
    ]
