# Generated by Django 4.2.1 on 2023-05-05 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_application_status_delete_statusapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friendss', to=settings.AUTH_USER_MODEL),
        ),
    ]
